#!name=波点音乐解锁VIP
#!desc=波点音乐 会员调试 + 去广告 + 下载歌曲(珍藏下载支持付费专辑导出文件) + 付费专辑解锁
#!author=WeiGiegie

[Script]
波点音乐 = type=http-response, pattern=^https?:\/\/(?:(?:bd-api|h5app|bodianyin|ab-bodian)\.kuwo\.cn\/(?:api\/(?:ucenter\/users\/(?:pub|login)|play\/(?:music\/v2\/(?:audioUrl|checkRight)|advert\/info)|service\/(?:music\/(?:info|download\/(?:info|config))|home\/module|global\/config\/(?:scene|vipEnter)|banner\/positions|advert\/config)|search\/topic\/word\/list|pay\/(?:vip\/(?:invitation\/(?:assist\/popup|swell)|lowPriceText)|sp\/actVip|audition\/url)|advert\/free\/config|popup\/start\/info|abtest\/ui\/info|rec\/feed)|abtest\/ui\/info)|us\.l\.qq\.com\/exapp|xs\.gdt\.qq\.com\/style_factory\/template_list), requires-body=1, max-size=3145728, script-path=https://raw.githubusercontent.com/woshitiancaihhh9/11/refs/heads/main/bodian.js

[MITM]
hostname = %APPEND% bd-api.kuwo.cn, *.kuwo.cn, *.kuwo.com, ad.tencentmusic.com, *.l.qq.com, h5app.kuwo.cn, bodianimgcdn.kuwo.cn, h5s.kuwo.cn, ab-bodian.kuwo.cn, xs.gdt.qq.com
